spring:
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sale?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xw123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  mail:
    username: 1304951263@qq.com
    nickname: 问天羽
    password: nuuveymxzxupiggi
    host: smtp.qq.com
    port: 465
    protocol: smtp
    default-encoding:  UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
